### ISSUE TITLE
ember 2.11.2 to type script and this addon

### ISSUE THREAD

**Issue by klclee** [emberwatch/ember-cli-typescript#13]
Am fairly new to TS and this plugin. I am trying to migrate a big project to this. However after installing everything when I do ` ember serve ` I am getting the following.. 

```
2017-03-05 09:48 ember[10417] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-03-05 09:48 ember[10417] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-03-05 09:48 ember[10417] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1028:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1361:11)
```

Sorry this could be a very simple question. Just looking to get started 👍

**Comment by chriskrycho** [comment]
@klclee just wanted you to know that I (the only person actively spending any time on this) have seen this issue you filed. I have no idea when I'll get to it (though you might try with the latest and see if it's still doing the same?), but it hasn't just vanished into the aether.

**Comment by chriskrycho** [comment]
@klclee and @gossi, can you try installing from master and seeing if it works for you now?

```bash
$ ember install https://github.com/emberwatch/ember-cli-typescript.git
$ ember generate ember-cli-typescript
$ ember serve
```

I *think* the tweaks we made in #30 may have resolved this issue.

**Comment by ivanvanderbyl** [comment]
I can confirm the changes made in #30 fixed this issue for me.

**Comment by locks** [comment]
Closing as we have two confirmed fixes. Feel free to reopen if you still encounter the issue @klclee!

**Comment by gossi** [comment]
Just tested. Works like charm ❤️
