### ISSUE TITLE
Broccoli Concat error, when files are removed or renamed

### ISSUE THREAD

**Issue by gossi** [emberwatch/ember-cli-typescript#57]
I'm on `1.0.0-beta.6` doing some very experimental testing with the `ember-module-unification-blueprint` in combination with `ember-cli-typescript`.  So whenever I rename a file or delete it, then I do get this error:

```
The Broccoli Plugin: [SimpleConcatConcat] failed with:
Error: ENOENT: no such file or directory, lstat ' <path to tmp folder of file before rename/delete>'


    at Object.fs.lstatSync (fs.js:947:11)
    at EslintValidationFilter.Filter.isDirectory (/path/to/project/node_modules/broccoli-persistent-filter/index.js:270:23)
    at EslintValidationFilter.Filter.getDestFilePath (/path/to/project/node_modules/broccoli-persistent-filter/index.js:275:12)
    at EslintValidationFilter.getDestFilePath (/path/to/project/node_modules/broccoli-lint-eslint/lib/index.js:125:55)
    at /path/to/project/node_modules/broccoli-persistent-filter/index.js:154:52
    at /path/to/project/node_modules/promise-map-series/index.js:11:14
    at tryCatch (/path/to/project/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/path/to/project/node_modules/rsvp/dist/rsvp.js:538:13)
    at /path/to/project/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/path/to/project/node_modules/rsvp/dist/rsvp.js:2415:5)

The broccoli plugin was instantiated at:
    at Concat.Plugin (/path/to/project/node_modules/broccoli-plugin/index.js:7:31)
    at new Concat (/path/to/project/node_modules/broccoli-concat/concat.js:38:10)
    at module.exports (/path/to/project/node_modules/broccoli-concat/index.js:26:10)
    at Function.EslintValidationFilter.create (/path/to/project/node_modules/broccoli-lint-eslint/lib/index.js:217:10)
    at Class.lintTree (/path/to/project/node_modules/ember-cli-eslint/index.js:44:19)
    at addons.reduce (/path/to/project/node_modules/ember-cli/lib/utilities/lint-addons-by-type.js:6:23)
    at Array.reduce (native)
    at lintAddonsByType (/path/to/project/node_modules/ember-cli/lib/utilities/lint-addons-by-type.js:4:17)
    at EmberApp.addonLintTree (/path/to/project/node_modules/ember-cli/lib/broccoli/ember-app.js:719:18)
    at EmberApp.lintTestTrees (/path/to/project/node_modules/ember-cli/lib/broccoli/ember-app.js:1345:28)
```

**Comment by chriskrycho** [comment]
Thanks for doing the experimenting!

This *may well* be something this addon needs to solve, but I want to check first: are you using broccoli-concat anywhere in the bits you're experimenting with? I ask in part because the addon expressly *doesn't* use broccoli-concat.

In general I see this same thing when renaming a file from `.js` to `.ts`, but I haven't observed it simply for removing files. I think it *may* lie deeper in the Ember CLI stack and setup, but I'm not sure. cc. @rwjblue @krisselden.

**Comment by ro0gr** [comment]
I'm pretty sure I see this issue on a regular base for the last three years. I think it's ember-cli related thing

**Comment by gossi** [comment]
I haven't installed something specifically to broccoli (e.g. broccoli-concat), it probably came with some dependencies. I used the `ember-module-unification-blueprint` installed my way up to `ember-cli-typescript`, `ember-decorators` and `babel-plugin-ember-modules-api-polyfill` (sorry, forgot to mention them in the first post) to end up with a cutting edge setup :D Well, what didn't work then, was using regular addons (I tried `ember-i18n`) and there were some drawbacks with `ember-decorators`, I switched back using _regular_ inject:

```
export default class Foo extends Bar {
   i18n = inject();
}
```

Regarding the workaround: I stopped ember, `rm -rf tmp/` and start `ember serve` again. What I might have seen later on, was just refreshing the page manually, which had the same effect. I did this on reflex, might be worth checking out the next time.

**Comment by chriskrycho** [comment]
Yeah, that's the same resolution I've had, and like @ro0gr (thanks for chiming in!) I see it with or without ember-cli-typescript, though I think because of the way the pipelines work it might be slightly more *common* with something like this (I expect ember-cli-coffeescript has the same issue).

I'm closing this as I'm fairly confident it's an upstream issue, but if someone gives us reason to think it *is* something we're doing wrong, I'll happily investigate!
